# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - content-management-system

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Create env-config.js
        run: |
          echo "window._env_ = { REACT_APP_API_BASE_URL: '${{ secrets.REACT_APP_API_BASE_URL }}' };" > ./content-management-system-app/public/env-config.js
      
      - name: Install dependencies and build
        working-directory: content-management-system-app
        run: |
          npm install
          npm run build

      - name: Debug environment variables
        run: |
          echo "Checking Environment Variables..."
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}"

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: content-management-system-app/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download build artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: ./content-management-system-app/build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3AB8E0F690584753BA6B30F20668B9A3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1D86D16E1EC545E9BBBABAAC0F9980A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9B524098A41456FBD19DC60CC44073F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'content-management-system'
          slot-name: 'Production'
          package: content-management-system-app/build/
